### ISSUE TITLE
CUDA out of memory training oobleck?

### ISSUE THREAD

**Issue by jbmaxwell** [Stability-AI/stable-audio-tools#11]
I've been very naively trying to piece together a training config for Oobleck, based partly on the `autoencoders` doc file and the `dac_2048_32_vae.json` example config. This is what I have now (which is *very* likely to be wrong!):

```

{
    "model_type": "autoencoder",
    "sample_size": 262144,
    "sample_rate": 48000,
    "audio_channels": 2,
    "model": {
        "encoder": {
            "type": "oobleck",
            "config": {
                "in_channels": 2,
                "channels": 128,
                "c_mults": [1, 2, 4, 8],
                "strides": [2, 4, 8, 8],
                "latent_dim": 128,
                "use_snake": true
            }
        },
        "decoder": {
            "type": "oobleck",
            "config": {
                "out_channels": 2,
                "channels": 128,
                "c_mults": [1, 2, 4, 8],
                "strides": [2, 4, 8, 8],
                "latent_dim": 64,
                "use_snake": true,
                "use_nearest_upsample": false
            }
        },
        "bottleneck": {
            "type": "l2_norm"
        },
        "latent_dim": 32,
        "downsampling_ratio": 2048,
        "io_channels": 1
    },
    "training": {
        "learning_rate": 1e-4,
        "warmup_steps": 0,
        "use_ema": false,
        "batch_size": 2,
        "loss_configs": {
            "discriminator": {
                "type": "encodec",
                "config": {
                    "filters": 32,
                    "n_ffts": [2048, 1024, 512, 256, 128, 64, 32],
                    "hop_lengths": [512, 256, 128, 64, 32, 16, 8],
                    "win_lengths": [2048, 1024, 512, 256, 128, 64, 32]
                },
                "weights": {
                    "adversarial": 0.1,
                    "feature_matching": 5.0
                }
            },
            "spectral": {
                "type": "mrstft",
                "config": {
                    "fft_sizes": [2048, 1024, 512, 256, 128, 64, 32],
                    "hop_sizes": [512, 256, 128, 64, 32, 16, 8],
                    "win_lengths": [2048, 1024, 512, 256, 128, 64, 32],
                    "perceptual_weighting": true
                },
                "weights": {
                    "mrstft": 1.0
                }
            },
            "time": {
                "type": "l1",
                "weights": {
                    "l1": 0.0
                }
            }
        },
        "demo": {
            "demo_every": 2000
        }
    }
}
```

Any suggestions? I think I initially tried removing the discriminator, but hit errors and added it back in.

**Comment by jbmaxwell** [comment]
Apologies, I see that `batch-size` is a command argument.

**Comment by jbmaxwell** [comment]
Actually, in case anybody sees this, I'm not hitting an error on a channel mismatch:
```
Traceback (most recent call last):
  File "/home/james/.vscode-server/extensions/ms-python.python-2023.19.12891009/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 3489, in <module>
    main()
  File "/home/james/.vscode-server/extensions/ms-python.python-2023.19.12891009/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 3482, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/james/.vscode-server/extensions/ms-python.python-2023.19.12891009/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2510, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/james/.vscode-server/extensions/ms-python.python-2023.19.12891009/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2517, in _exec
    globals = pydevd_runpy.run_path(file, globals, '__main__')
  File "/home/james/.vscode-server/extensions/ms-python.python-2023.19.12891009/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/james/.vscode-server/extensions/ms-python.python-2023.19.12891009/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/james/.vscode-server/extensions/ms-python.python-2023.19.12891009/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/james/src/somms/stable-audio-tools/train.py", line 100, in <module>
    main()
  File "/home/james/src/somms/stable-audio-tools/train.py", line 97, in main
    trainer.fit(training_wrapper, train_dl, ckpt_path=args.ckpt_path if args.ckpt_path else None)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 221, in advance
    batch_output = self.manual_optimization.run(kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/manual.py", line 91, in run
    self.advance(kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/manual.py", line 111, in advance
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 330, in training_step
    return self.model(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/pytorch_lightning/overrides/base.py", line 90, in forward
    output = self._forward_module.training_step(*inputs, **kwargs)
  File "/home/james/src/somms/stable-audio-tools/stable_audio_tools/training/autoencoders.py", line 199, in training_step
    decoded = self.autoencoder.decode(latents)
  File "/home/james/src/somms/stable-audio-tools/stable_audio_tools/models/autoencoders.py", line 330, in decode
    decoded = self.decode_fn(latents, self.decoder, **kwargs)
  File "/home/james/src/somms/stable-audio-tools/stable_audio_tools/models/autoencoders.py", line 269, in <lambda>
    decode_fn: Callable[[torch.Tensor, nn.Module], torch.Tensor] = lambda x, decoder: decoder(x),
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/james/src/somms/stable-audio-tools/stable_audio_tools/models/autoencoders.py", line 220, in forward
    return self.layers(x)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/james/anaconda3/envs/torch_sat/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [512, 64, 7], expected input[2, 128, 512] to have 64 channels, but got 128 channels instead
```

**Comment by jbmaxwell** [comment]
Note to future travellers: `32768` is sufficient for AE training (my `262144` was massive overkill—this is a more appropriate duration for diffusion training, not the AEI).

**Comment by cryptowooser** [comment]
@jbmaxwell Thank you for noting this, it saved me from a nasty OOM  that was stumping me.
