### ISSUE TITLE
ResolutionTooDeep

### ISSUE THREAD

**Issue by Apple-jun** [Stability-AI/stable-audio-tools#158]
When I run pip install stable-audio-tools, I repeatedly encounter the following issue：
Collecting gradio>=3.42.0 (from stable-audio-tools)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/83/db/578e4b4f79dc1ef0d81a7c54fdede4a0b57a0b4feec4b003f4ef86a99629/gradio-4.28.3-py3-none-any.whl (12.2 MB)
Collecting gradio-client==0.16.0 (from gradio>=3.42.0->stable-audio-tools)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/9e/f9/8b979f230b15455dbec422756e7e8975c6675276ddc9aaa3c2c730d867d3/gradio_client-0.16.0-py3-none-any.whl (314 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/root/miniconda3/envs/stable2/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/root/miniconda3/envs/stable2/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "/root/miniconda3/envs/stable2/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/root/miniconda3/envs/stable2/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "/root/miniconda3/envs/stable2/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/root/miniconda3/envs/stable2/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/root/miniconda3/envs/stable2/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
Any help would be appreciated.

**Comment by jrohsc** [comment]
I'm facing the same error

pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
