### ISSUE TITLE
train.py: KeyError: 'pytorch-lightning_version'

### ISSUE THREAD

**Issue by HughPH** [Stability-AI/stable-audio-tools#163]
If I'm reading this correctly, it's complaining that `model.ckpt` from the hf repo doesn't have a "pytorch-lightning_version" member?

```
KeyError: 'pytorch-lightning_version'
Traceback (most recent call last):
  File "/mnt/store2/stable-audio-tools/./train.py", line 128, in <module>
    main()
  File "/mnt/store2/stable-audio-tools/./train.py", line 125, in main
    trainer.fit(training_wrapper, train_dl, ckpt_path=args.ckpt_path if args.ckpt_path else None)
  File "/home/hugh/anaconda3/envs/stable-audio-tools/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/hugh/anaconda3/envs/stable-audio-tools/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugh/anaconda3/envs/stable-audio-tools/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/hugh/anaconda3/envs/stable-audio-tools/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 956, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/hugh/anaconda3/envs/stable-audio-tools/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 395, in _restore_modules_and_callbacks
    self.resume_start(checkpoint_path)
  File "/home/hugh/anaconda3/envs/stable-audio-tools/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 80, in resume_start
    self._loaded_checkpoint = _pl_migrate_checkpoint(loaded_checkpoint, checkpoint_path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugh/anaconda3/envs/stable-audio-tools/lib/python3.11/site-packages/pytorch_lightning/utilities/migration/utils.py", line 142, in _pl_migrate_checkpoint
    old_version = _get_version(checkpoint)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugh/anaconda3/envs/stable-audio-tools/lib/python3.11/site-packages/pytorch_lightning/utilities/migration/utils.py", line 163, in _get_version
    return checkpoint["pytorch-lightning_version"]
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'pytorch-lightning_version'
```

**Comment by HughPH** [comment]
unwrap_model.py gives me the same error.

**Comment by HughPH** [comment]
Turns out that ckpt is already unwrapped
