### ISSUE TITLE
Fail to train dac with rvq model in multi-gpu

### ISSUE THREAD

**Issue by didadida-r** [Stability-AI/stable-audio-tools#20]
hi,

i try to train the dac VAE, but i turns out nan loss in epoch3, then i train the dac RVQ, but i can only train on single gpu, multi gpu will fail. 

i train the dac VAE because the musicgen model training require such compression component, but there is not offical config of the dac RVQ.

Thanks for your kind help

the detail log of the dac RVQ is
```
Epoch 0:   0%| | 2/48248 [00:15<106:04:35,  7.92s/it, v_num=q5e6, train/loss=8.820, train/mrstft_loss=7.590, train/l1_time_loss=0.000, train/loss_adv=-.00369, train/feature_matching=0.145, train/latenRuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 6 13 20 27 34 41 48 55
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/torchaudio/transforms/_transforms.py:580: UserWarning: Argument 'onesided' has been deprecated and has no influence on the behavior of this module.
  warnings.warn(
/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/torchaudio/functional/functional.py:584: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (128) may be set too high. Or, the value for `n_freqs` (513) may be set too low.
  warnings.warn(
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 6 13 20 27 34 41 48 55
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 3: 6 13 20 27 34 41 48 55
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
Traceback (most recent call last):
  File "/home/test/code/audio/test/stable-audio-tools/egs/RVQ_dac/src/train.py", line 103, in <module>
    main()
  File "/home/test/code/audio/test/stable-audio-tools/egs/RVQ_dac/src/train.py", line 100, in main
    trainer.fit(training_wrapper, train_dl, ckpt_path=args.ckpt_path if args.ckpt_path else None)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 221, in advance
    batch_output = self.manual_optimization.run(kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/manual.py", line 91, in run
    self.advance(kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/manual.py", line 111, in advance
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 330, in training_step
    return self.model(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1515, in forward
    inputs, kwargs = self._pre_forward(*inputs, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1409, in _pre_forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: It looks like your LightningModule has parameters that were not used in producing the loss returned by training_step. If this is intentional, you must enable the detection of unused parameters in DDP, either by setting the string value `strategy='ddp_find_unused_parameters_true'` or by setting the flag in the strategy with `strategy=DDPStrategy(find_unused_parameters=True)`.
Traceback (most recent call last):
  File "/home/test/code/audio/test/stable-audio-tools/egs/RVQ_dac/src/train.py", line 103, in <module>
    main()
  File "/home/test/code/audio/test/stable-audio-tools/egs/RVQ_dac/src/train.py", line 100, in main
    trainer.fit(training_wrapper, train_dl, ckpt_path=args.ckpt_path if args.ckpt_path else None)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 221, in advance
    batch_output = self.manual_optimization.run(kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/manual.py", line 91, in run
    self.advance(kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/manual.py", line 111, in advance
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 330, in training_step
    return self.model(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1515, in forward
    inputs, kwargs = self._pre_forward(*inputs, **kwargs)
  File "/home/test/python_env/anaconda3/envs/StableAudio/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1409, in _pre_forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
```

the detail config of the dac RVQ is 
```
"model_type": "autoencoder",
    "sample_size": 16384,
    "sample_rate": 48000,
    "audio_channels": 1,
    "model": {
        "encoder": {
            "type": "dac",
            "config": {
                "latent_dim": 32,
                "d_model": 128,
                "strides": [4, 4, 8, 8]
            }
        },
        "decoder": {
            "type": "dac",
            "config": {
                "latent_dim": 32,
                "channels": 1024,
                "rates": [8, 4, 8, 4]
            }
        },
        "bottleneck": {
            "type": "dac_rvq",
            "config": {
                "input_dim": 32,
                "n_codebooks": 8,
                "codebook_dim": 32,
                "codebook_size": 1024,
                "quantizer_dropout": 0.0
            }
        },
        "latent_dim": 32,
        "downsampling_ratio": 1024,
        "io_channels": 1
    },
```

**Comment by zqevans** [comment]
you'll want to set `--strategy ddp_find_unused_parameters_true` in the command line parameters for train.py
