### ISSUE TITLE
`ImportError: cannot import name 'packaging' from 'pkg_resources'` from `run_gradio.py`

### ISSUE THREAD

**Issue by YoungPhlo** [Stability-AI/stable-audio-tools#66]
Traceback:
```python
(venv) PS stable-audio-tools> python run_gradio.py --ckpt-path ./models/model.ckpt --model-config ./models/model_config.json
Traceback (most recent call last):
  File "run_gradio.py", line 2, in <module>
    from stable_audio_tools.interface.gradio import create_ui
  File "stable-audio-tools\stable_audio_tools\interface\gradio.py", line 14, in <module>
    from ..inference.generation import generate_diffusion_cond, generate_diffusion_uncond
  File "stable-audio-tools\stable_audio_tools\inference\generation.py", line 8, in <module>
    from .sampling import sample, sample_k
  File "stable-audio-tools\stable_audio_tools\inference\sampling.py", line 5, in <module>
    import k_diffusion as K
  File "stable-audio-tools\venv\lib\site-packages\k_diffusion\__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "stable-audio-tools\venv\lib\site-packages\k_diffusion\evaluation.py", line 6, in <module>
    import clip
  File "stable-audio-tools\venv\lib\site-packages\clip\__init__.py", line 1, in <module>
    from .clip import *
  File "stable-audio-tools\venv\lib\site-packages\clip\clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (stable-audio-tools\venv\lib\site-packages\pkg_resources\__init__.py)
```

They're having the same issue over on https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15863

Something about the `setuptools==70.0.0` release broke `pkg_resources` and it looks like there are no plans to fix it... Not sure where that leaves `clip`

The command that worked for me is
`python -m pip install setuptools==69.5.1`

(with the `stable-audio-tools` venv activated)

I can run `python run_gradio.py` plus arguments and it works after downgrading.

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/Stability-AI/stable-audio-tools/issues/74

**Comment by 0xdevalias** [comment]
> > You could also check how NanoCoder installed flash-attn mentioned at the end of [this post](https://github.com/Stability-AI/stable-audio-tools/issues/73#issuecomment-2151566689)
> 
> The relevant part seems to be related to `setuptools`:
> 
> > Thanks! a clean env solved it.
> > 
> > On a clean env, I additionally had to install
> > 
> > ```bash
> > # ..snip..
> > 
> > # for packaging error `cannot import name 'packaging' from 'pkg_resources'`
> > pip install -U packaging
> > pip install setuptools==69.5.1
> > 
> > # ..snip..
> > ```
> > 
> > _Originally posted by @NanoCode012 in https://github.com/Stability-AI/stable-audio-tools/issues/73#issuecomment-2151566689_
> 
> Following from that, to the official `setuptools` GitHub repo, and searching for the error there, leads me to issues such as these:
> 
> - https://github.com/pypa/setuptools/issues/4376
>   - > `69.5.1` had `packaging.pkg_resources`. I can run `from pkg_resources import packaging`.
>     >
>     > But `70.0.0` seems to remove `packaging.pkg_resources`. Running `from pkg_resources import packaging` errors with `ImportError: cannot import name 'packaging' from 'pkg_resources'`.
>   - https://github.com/pypa/setuptools/issues/4376#issuecomment-2123274240
>     - > The fact that users were trying to run `from pkg_resources import packaging`, means that they were relying on a side-effect/implementation detail of `pkg_resources`, and that is not guaranteed to be stable between releases.
> - https://github.com/pypa/setuptools/issues/4385
>   - https://github.com/pypa/setuptools/issues/4385#issuecomment-2126286321
>     - > Tl;DR: the package you are using was relying on an internal implementation detail of pkg_resources and that implementation detail was not part of the public API.
>       > 
>       > I recommend contacting the maintainers of that package and reporting the bug on their end. The easiest way to fix this is to install and import [packaging](https://packaging.pypa.io/en/stable/) directly.
> 
> So as I read that, the solutions are either to:
> 
> - continue to use an older version of `setuptools` as a workaround/hack to make the existing code work (not recommended)
>   - See the quoted 'fix' above
> - update the code + install the relevant packages yourself (recommended)
>   - Use the solution @Abhijitjimmi provided above in https://github.com/Stability-AI/stable-audio-tools/issues/74#issuecomment-2159267427:
>   - > edit the line with this 
> 	> 
> 	> ```
> 	> import packaging
> 	> ```
> 	> 
> 	> its no more `from pkg_resources`
> 	> 
> 	> _Originally posted by @Abhijitjimmi in https://github.com/Stability-AI/stable-audio-tools/issues/74#issuecomment-2159267427_
> 
> _Originally posted by @0xdevalias in https://github.com/Stability-AI/stable-audio-tools/issues/74#issuecomment-2164143964_

**Comment by skirdey** [comment]
After installing OpenAI's clip it works

pip install git+https://github.com/openai/CLIP.git
