### ISSUE TITLE
Windows gradio UI issue - ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by SoftologyPro** [Stability-AI/stable-audio-tools#72]
I change into the `stable-audio-tools\stable_audio_tools\interface\` directory and run `python gradio.py`
Gives this error
```
D:\Tests\Stable Audio Tools\stable-audio-tools\stable_audio_tools\interface>python gradio.py
Traceback (most recent call last):
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\stable_audio_tools\interface\gradio.py", line 3, in <module>
    import gradio as gr
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\stable_audio_tools\interface\gradio.py", line 14, in <module>
    from ..inference.generation import generate_diffusion_cond, generate_diffusion_uncond
ImportError: attempted relative import with no known parent package
```
Something with the `..` reference does not work on Windows?
The inference folder `stable-audio-tools\stable_audio_tools\inference` does exist.

**Comment by hushaudio** [comment]
Use the run_gradio.py from the root of the repo.  You can view the file to see what arguments are supported.  Make sure to use —pretrained-ckpt-path for the base model. Fine tuned and unwrapped use —ckpt-path

**Comment by SoftologyPro** [comment]
Thanks.  There is no `pretrained-ckpt-path` parameter.  Using that gives
```
usage: run_gradio.py [-h] [--pretrained-name PRETRAINED_NAME] [--model-config MODEL_CONFIG] [--ckpt-path CKPT_PATH] [--pretransform-ckpt-path PRETRANSFORM_CKPT_PATH] [--username USERNAME] [--password PASSWORD] [--model-half]
run_gradio.py: error: unrecognized arguments: --pretrained-ckpt-path .\ckpt
```
Trying to use `pretransform-ckpt-path` instead gives
```
Traceback (most recent call last):
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\run_gradio.py", line 31, in <module>
    main(args)
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\run_gradio.py", line 10, in main
    interface = create_ui(
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\stable_audio_tools\interface\gradio.py", line 659, in create_ui
    assert (pretrained_name is not None) ^ (model_config_path is not None and ckpt_path is not None), "Must specify either pretrained name or provide a model config and checkpoint, but not both"
AssertionError: Must specify either pretrained name or provide a model config and checkpoint, but not both
```
I have the models downloaded and inside a ckpt folder.

**Comment by hushaudio** [comment]
Yes it’s pretransform my bad, you need to include the model config too. Let me know how it goes!

**Comment by SoftologyPro** [comment]
What exact syntax do I need to use.
This
`python run_gradio.py --pretransform-ckpt-path ".\ckpt" --model-config ".\ckpt"`
gives this
```
Traceback (most recent call last):
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\run_gradio.py", line 31, in <module>
    main(args)
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\run_gradio.py", line 10, in main
    interface = create_ui(
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\stable_audio_tools\interface\gradio.py", line 659, in create_ui
    assert (pretrained_name is not None) ^ (model_config_path is not None and ckpt_path is not None), "Must specify either pretrained name or provide a model config and checkpoint, but not both"
AssertionError: Must specify either pretrained name or provide a model config and checkpoint, but not both
```
The model files are inside a ckpt folder directly under the root directory where `run_gradio.py` is .

**Comment by hushaudio** [comment]
Use python run_gradio.py --pretransform-ckpt-path=".\ckpt\model.ckpt" --model-config=".\ckpt\model-config.json"

You may not need quotes I don’t remember. May work without = too but I think this is right

**Comment by SoftologyPro** [comment]
With or without the = gives
```
Traceback (most recent call last):
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\run_gradio.py", line 31, in <module>
    main(args)
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\run_gradio.py", line 10, in main
    interface = create_ui(
  File "D:\Tests\Stable Audio Tools\stable-audio-tools\stable_audio_tools\interface\gradio.py", line 659, in create_ui
    assert (pretrained_name is not None) ^ (model_config_path is not None and ckpt_path is not None), "Must specify either pretrained name or provide a model config and checkpoint, but not both"
AssertionError: Must specify either pretrained name or provide a model config and checkpoint, but not both
```

**Comment by SoftologyPro** [comment]
OK, got it.
Put models under ckpt then run with
python run_gradio.py --ckpt-path ".\ckpt\model.ckpt" --model-config ".\ckpt\model_config.json"

**Comment by hushaudio** [comment]
Sorry I was thinking of training commands, I was out for dinner.  Glad you got it sorted!

**Comment by SoftologyPro** [comment]
Also a minor suggestion.  Share should be off by default for security reasons.
