### ISSUE TITLE
 ModuleNotFoundError: No module named 'packaging' from pip install stable-audio-tools

### ISSUE THREAD

**Issue by w84death** [Stability-AI/stable-audio-tools#74]
```
 Downloading flash_attn-2.5.9.post1.tar.gz (2.6 MB)
     ---------------------------------------- 2.6/2.6 MB 6.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\StableAudio\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\StableAudio\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\StableAudio\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Krzysztof Jankowski\AppData\Local\Temp\pip-build-env-e_t_1lmm\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Krzysztof Jankowski\AppData\Local\Temp\pip-build-env-e_t_1lmm\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Krzysztof Jankowski\AppData\Local\Temp\pip-build-env-e_t_1lmm\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Krzysztof Jankowski\AppData\Local\Temp\pip-build-env-e_t_1lmm\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Same error on:
- Ubuntu
- Windows 10 (miniconda3)

Both using venv.

**Comment by hushaudio** [comment]
The issue is with your systems compatibility with the package flash_atn

If it can’t build the wheel it means something is not compatible.  On windows, WSL uses Ubuntu which should fix the issue, but I haven’t worked on windows 10 just windows 11 which uses WSL2. You should be looking into flash_attn tho and compatibility with your system.

**Comment by hushaudio** [comment]
You could also check how NanoCoder installed flash-attn mentioned at the end of [this post](https://github.com/Stability-AI/stable-audio-tools/issues/73#issuecomment-2151566689)

**Comment by Skquark** [comment]
I'm also getting this issue trying to install on Windows in a venv.  I've tried switching to multiple version of packaging and setuptools, but just can't find the key to installing it.
Also having a bunch of issues trying to install stable-audio-tools on Google Colab, getting multiple conflicts like numpy, argparse, protobuf, cuda, etc. Then it needs to restart session, which I do and try installing again, but it still doesn't work, asking to restart again.  Hate dealing with versioning conflicts, especially when trying to integrate in an existing project that has many other pinned dependencies with packages we have no control over..

**Comment by w84death** [comment]
@hushaudio thanks! unfortunately I ran into same problem in the end.

**Comment by fred-dev** [comment]
> I'm also getting this issue trying to install on Windows in a venv.  I've tried switching to multiple version of packaging and setuptools, but just can't find the key to installing it.
> 
> Also having a bunch of issues trying to install stable-audio-tools on Google Colab, getting multiple conflicts like numpy, argparse, protobuf, cuda, etc. Then it needs to restart session, which I do and try installing again, but it still doesn't work, asking to restart again.  Hate dealing with versioning conflicts, especially when trying to integrate in an existing project that has many other pinned dependencies with packages we have no control over..

You can use a venv in google colab  and this will get rid of the issues you have there. Miniconda works fine for me. The setup is marginally longer but not a big deal.

As for the flash attention, this library has specific hardware requirements, it will give errors if your hardware does not support flash attention. I have seen some cases where the code designed to pickup the hardware (GPU) version and deal with flash attention initialisation does not work. I have made a temporary workaround by forcing flash attention off in the checks. I suspect the driver version reports are also linked to cuda versions and this is why the detection does not always report correctly, but I have not had time to check this. 

A temporary hack is to search the flash attention initialisation and force it off. Alternatively some research into version reporting is needed to make this more reliable. 

You will find that on later hardware you will not have this issue.

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/Stability-AI/stable-audio-tools/issues/66

**Comment by Abhijitjimmi** [comment]
edit the line with this 
import packaging
its no more from pkg_resources

**Comment by joerg-knitter** [comment]
I get the same error message on Windows 11 with Python 3.12.4, using a clean venv with setuptools downgraded to 69.5.1.
Where should I edit the import packaging line?

**Comment by 0xdevalias** [comment]
> You could also check how NanoCoder installed flash-attn mentioned at the end of [this post](https://github.com/Stability-AI/stable-audio-tools/issues/73#issuecomment-2151566689)

The relevant part seems to be related to `setuptools`:

> Thanks! a clean env solved it.
> 
> On a clean env, I additionally had to install
> 
> ```bash
> # ..snip..
> 
> # for packaging error `cannot import name 'packaging' from 'pkg_resources'`
> pip install -U packaging
> pip install setuptools==69.5.1
> 
> # ..snip..
> ```
> 
> _Originally posted by @NanoCode012 in https://github.com/Stability-AI/stable-audio-tools/issues/73#issuecomment-2151566689_

Following from that, to the official `setuptools` GitHub repo, and searching for the error there, leads me to issues such as these:

- https://github.com/pypa/setuptools/issues/4376
  - > `69.5.1` had `packaging.pkg_resources`. I can run `from pkg_resources import packaging`.
    >
    > But `70.0.0` seems to remove `packaging.pkg_resources`. Running `from pkg_resources import packaging` errors with `ImportError: cannot import name 'packaging' from 'pkg_resources'`.
  - https://github.com/pypa/setuptools/issues/4376#issuecomment-2123274240
    - > The fact that users were trying to run `from pkg_resources import packaging`, means that they were relying on a side-effect/implementation detail of `pkg_resources`, and that is not guaranteed to be stable between releases.
- https://github.com/pypa/setuptools/issues/4385
  - https://github.com/pypa/setuptools/issues/4385#issuecomment-2126286321
    - > Tl;DR: the package you are using was relying on an internal implementation detail of pkg_resources and that implementation detail was not part of the public API.
      > 
      > I recommend contacting the maintainers of that package and reporting the bug on their end. The easiest way to fix this is to install and import [packaging](https://packaging.pypa.io/en/stable/) directly.

So as I read that, the solutions are either to:

- continue to use an older version of `setuptools` as a workaround/hack to make the existing code work (not recommended)
  - See the quoted 'fix' above
- update the code + install the relevant packages yourself (recommended)
  - Use the solution @Abhijitjimmi provided above in https://github.com/Stability-AI/stable-audio-tools/issues/74#issuecomment-2159267427:
  - > edit the line with this 
	> 
	> ```
	> import packaging
	> ```
	> 
	> its no more `from pkg_resources`
	> 
	> _Originally posted by @Abhijitjimmi in https://github.com/Stability-AI/stable-audio-tools/issues/74#issuecomment-2159267427_
